### ISSUE TITLE
Fix compilation error: unexpected `cfg` condition value: `__abi-embed-checked`

### ISSUE THREAD

**Issue by frol** [near/near-sdk-rs#1223]
[CI fails](https://github.com/near/near-sdk-rs/actions/runs/10140282020/job/28035171785) in main branch are caused by the recent Rust 1.80 release that introduced cfg features checks:

<img width="801" alt="image" src="https://github.com/user-attachments/assets/7fdbb82b-9b08-4ccb-8a94-f2a8dc3a24b9">

https://blog.rust-lang.org/2024/07/25/Rust-1.80.0.html

We need to review the feature names and either properly name them, or add them to Cargo.toml.

**Comment by lauchaves** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/near-sdk-rs).

### My background and how it can be leveraged
Hey! I'm Lau Chaves, and I would like to contribute to this issue!

I just noticed it as well running it locally and also on the PR I just created, I was gonna ask about it, thought it was related to the other pull request that hasn’t been merged. 

But now that I’ve context, I’d love to give it a try! 

### How I plan on tackling this issue
Here’s the approach I’d follow:

- First I would review the error messages and identify which parts of the code are failing due to the new cfg features checks.
- I’ll look for #[cfg(...)] and #[cfg_attr(...)] 
- I’ll  review the Rust 1.80 release notes to understand the specific changes to cfg feature checks
- I’ll update configuration, check .toml to ensure it’s defined correctly 
- I’ll fix all the cfg that are misconfigured
- I’ll run tests in order to check that issues are resolved and no new issues have been introduced

**Comment by frol** [comment]
@lauchaves See this comment with a potential solution being proposed: https://t.me/NEAR_Tools_Community_Group/2774

**Comment by frol** [comment]
@lauchaves yes, that one line fix addresses the first compilation error, but there are more, please, pick it up from there: https://github.com/near/near-sdk-rs/pull/1225

**Comment by lauchaves** [comment]
@frol alright, will do!
