### ISSUE TITLE
[Feature Request] An 'owner' macro to ensure methods are called by owner

### ISSUE THREAD

**Issue by willemneal** [near/near-sdk-rs#194]
This should be the first function called.
```rust
fn assert_owner(&self) {
  assert_eq!(
            env::predecessor_account_id(),
            self.owner_id,
            "Can only be called by the owner"
        );
    }
```

**Comment by willemneal** [comment]
https://github.com/near/core-contracts/issues/73#issuecomment-649091675

**Comment by KaiserKarel** [comment]
Something like a proc-macro perhaps?

```
#[restricted(owner)]
fn kill() { ... }
```

**Comment by austinabell** [comment]
Not sure this is great to add to the API, since owner is very application-specific and not any concept tied to the SDK. Perhaps this would be better if we could create some system of modifiers for function calls so that this could be better expressed.

The issue with doing this is that you would need to infer the `owner_id` field name on state, which is too loose of a connection. Perhaps there could be some connection if you also add an annotation on the struct itself, but it seems like a more general solution would be much more maintainable. I'm going to close this, but feel free to re-open it if you have an idea of how this could be done without assumptions

**Comment by willemneal** [comment]
Really this is asserting a caller.  So perhaps an easy solution is to use @KaiserKarel's example

```rs
#[assert_caller(owner_id)]
fn kill() { ... }
```

**Comment by austinabell** [comment]
> Really this is asserting a caller. So perhaps an easy solution is to use @KaiserKarel's example
> 
> ```rust
> #[assert_caller(owner_id)]
> fn kill() { ... }
> ```

This isn't intuitive that `owner_id` is coming from state, though. I think if we can come up with a more general solution it would be better than handling it for every specific case (in this one, asserting predecessor) since we already have `#[private]` to handle a very specific sub-case of this.

**Comment by willemneal** [comment]
Could add `self.owner_id` then.  The macro is already on a method of the struct so that should make it clear.  Could just even add it to private.
