### ISSUE TITLE
Improve testing / introduce Rust API

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-sdk-rs#233]
So currently we are wriitng method names in string and passing arguments in JSON. In integration tests this leads to a weird json parsing errors when things don't match.

We are also introducing more borsh arguments for method names. Which means soon we will end up with ABIs pretty much.

Suggestion to add a set of marcos and tools to infer the API for using contracts.
This also will serve not just for testing but also as rust-api-rs, which we currently don't have.

```
#[derive_json_abi]
struct FungibleToken {
    pub fn new();
    pub fn transfer(&mut self);
    pub fn transferFrom(&mut self, …);
    pub fn balanceOf(&self, owner_id: AccountId) -> Balance;
}
```
OR
```#[derive_borsh_abi]```
OR
``` 
load_abi!(FungibleToken, 'path/to/abi');
```
and then
```
let mut contract = FungibleToken::???(runtime, contract_account_id); // this would just create a contract object for given 
```
OR
```
// This would deploy contract, call new and create a object.
let mut contract = FungibleToken::deploy(runtime, signer_id, code, /* args for new call */);
```

Can use then:
```
contract.transfer(signer_id, to_id, amount);
contract.balanceOf(owner_id);
etc
```

We can hide signer into contract when creating one, but it’s a bit confusing in JS IMO.

Given runtime has very similar API to our RPC, this APIs should take a trait in which StandaloneRuntime and RustRPCProvider can implement.

**Comment by willemneal** [comment]
Makes sense and it will fix the current issues I have with the generated macros not being expanded in the IDE.  The ABI could also generate a JS file with an associated types `d.ts` file.  This way front end users will have the same API.  Furthermore we could still reuse the `near_bindgen` macro and just generate the file when building the contract. 



How about something like

```rust
let alice = runtime.create_user("alice".into", initial_balance)
let contract = runtime.deploy_and_init(runtime, contract_id, code, FungibleToken::new(...args);
// ^ signer_id is runtime's root
let pending_tx = contract.transfer("new_owner".into(), to_yocto(&"1000000");
let res = alice.call(pending_tx, to_yocto("0"), DEFAULT_GAS);
```
The idea here is that the generated contract will return a type like:

```rust

struct PendingContractTx {
  pub receiever_id: AccountId,
  pub method: str,
  pub args: Vec<u8>,
  pub is_view: boolean,
}
/// And the user type
struct User<'a> {
  account_id: AccountId
  signer: InMemorySigner,
  runtime: &'a mut Runtime,
}
```

This way the methods are just responsible for preparing for the call and then the user's `call` method will make the call using the user's `account_id` and `signer`.

```rust
runtime.view(contract.balanceOf(alice.account_id()), DEFAULT_GAS)
```

Here we could get a check that the method is a view method too.

Alternatively we could have the call method on the pending transaction (and need to add a reference to the runtime in its struct)

```rust

struct PendingContractTx<'a> {
  pub receiever_id: AccountId,
  pub method: str,
  pub args: Vec<u8>,
  pub is_view: boolean,
  runtime: &'a mut Runtime
}

let res = contract.transfer("new_owner".into(), to_yocto(&"1000000").call(alice, to_yocto("0"), DEFAULT_GAS);
/// And the view

let res = contract.balanceOf(alice.account_id()).view(DEFAULT_GAS);
```

Lastly, we currently always process all the blocks when issuing a transaction.  Should we also provide a way execute just a step so that the user can see the intermediate receipts, etc?

**Comment by chadoh** [comment]
Something that I've done a lot in unit tests that I anticipate doing even more in robust integration tests is change who's calling the function all over the place. "Given Alice has balance X, and given Alice grants Bob access to control Y, then when Bob calls, ..."

So whatever we do here, I want to make sure that use-case feels natural.

This seems:

```rust
let pending_tx = contract.transfer("new_owner".into(), to_yocto(&"1000000");
let res = alice.call(pending_tx, to_yocto("0"), DEFAULT_GAS);
```

I'm surprised to see "attached gas" and "attached amount" in the `alice.call` part, since I think of them as arguments I can pass to a contract call, but maybe that's fine. I'd prefer named arguments in the `alice.call`, so I don't have to pass argument 2 if I only want to pass argument 3. Also, are those arguments in the wrong order? What's `to_yocto("0")`?

**Comment by bowenwang1996** [comment]
> I'd prefer named arguments in the alice.call

Are you suggesting that we use a struct here instead? There is no named arguments in rust.

**Comment by willemneal** [comment]
@chadoh We could also make the last two args options,

```rust

let res = alice.call(pending_tx, None, Some(DEFAULT_GAS));
```

Alternatively we could add them as fields, and they are set to default values:


```rust
struct PendingContractTx<'a> {
  pub receiever_id: AccountId,
  pub method: str,
  pub args: Vec<u8>,
  pub is_view: boolean,
  runtime: &'a mut Runtime,
  pub gas: Gas,
  pub attached_deposit: Balance
}

impl PendingContractTx {
  set_gas(mut self, gas: Gas) -> Self {
    self.gas = gas;
    self 
  }
  
  set_attached_deposit(mut self, balance: Balance) -> Self {
    self.attached_deposit = balance;
    self
  }
}
```

Then use methods to change the fields:

```rust
le pending_tx = contract.transfer("new_owner".into(), to_yocto(&"1000000"))
                            .set_gas(DEFAULT_GAS)
                            .set_attached_deposit(to_yocto("0"));
let res = alice.call(pending_tx);

```
