### ISSUE TITLE
Multiple contracts in one cargo example

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-sdk-rs#255]
Is there a way to create multiple contracts from a single cargo?
There are some things that get harder as more cargos are introduced into the project. 

Specifically some testing. Additionally it dilutes the project if for each testing contract need to introduce new 4-5 files.

**Comment by austinabell** [comment]
There currently is not. Each cargo [can only specify one lib](https://doc.rust-lang.org/cargo/reference/cargo-targets.html#configuring-a-target). You can with multiple binaries, but that doesn't work in this case. I don't think there is currently a way to do this.

There is also this thread https://internals.rust-lang.org/t/multiple-libraries-in-a-cargo-project/8259/13 which @matklad gave good input on, so maybe he knows if anything has changed since then to make this possible :) 

Going to close as it doesn't seem like anything can be done here though
