### ISSUE TITLE
log in host side with simulator

### ISSUE THREAD

**Issue by ailisp** [near/near-sdk-rs#317]
When doing cross contract call, `near_sdk::log!` or `env::log` in the caller contract won't show up in final outcome. However it would be helpful to debug print these logs with simulator

**Comment by willemneal** [comment]
You can access the results of the promises with `promise_results`.

https://github.com/near/near-sdk-rs/blob/330d161b68ba80280fdbc02facd7f0744bd36d48/near-sdk-sim/src/outcome.rs#L124

Which contains the outcomes of each promise created since the initial transaction, which then contains the logs, but perhaps we should add another method to access just the logs as this will be a common case.

**Comment by ailisp** [comment]
Thanks, with this I don't need a "log in simulator" functionality
