### ISSUE TITLE
Possible callback function addition on deposit.

### ISSUE THREAD

**Issue by jasperdg** [near/near-sdk-rs#40]
In Solidity a developer has the option to add a callback function to their code, what this would allow for would be the following:

```
 contract MyContract {
 deposit(address _from, int256 _amount ) public 

 {...} 

 // Handles deposits

 // Callback on transfer to MyContract
 function () payable 

 { // Do something here, for example: revert(); // return users money because this contract should not take any deposits without calling the deposit method } 

}
 ```

You could instead of just reverting the transaction also treat the transfers as deposits:
 ```
 function () payable 

 { // Or what you could do is: deposit(msg.sender, msg.value); // Deposits the funds to the contract but also make sure to keep track of it using the deposit method } 

```

Taking this last example, if we have `alice` and a contract called `bobs_contract` instead of having to call the deposit method on `bobs_contract`(which is impossible with near-wallet/lib right now which is why I came up with this workaround for reference: <span class="error">[this issue]</span>([https://github.com/nearprotocol/near-wallet/issues/56](https://github.com/nearprotocol/near-wallet/issues/56))) `alice` can just transfer _n_ amount of tokens to `bobs_contract`, and have it be treated as calling the deposit method.

**Comment by nearmax** [comment]
In Near Protocol financial transactions of native tokens are treated separately from the contract calls. Specifically, when Alice transfers tokens to Bob it does not trigger Bob's contract execution which is actually very beneficial for the users and the developers since contract execution costs at least 2x more gas than a token transfer. For this reason, we cannot call any method on Bob's account when it receives a simple token transfer from Alice.

**Comment by austinabell** [comment]
Closing, seems unactionable
