### ISSUE TITLE
Smart contract panicked: The collection is an inconsistent state

### ISSUE THREAD

**Issue by evergreen-trading-systems** [near/near-sdk-rs#560]
ExecutionError: 'Smart contract panicked: The collection is an inconsistent state. Did previous smart contract execution terminate unexpectedly?

https://github.com/evergreen-trading-systems/near-sdk-lookupmap-bug

`LookupMap` can't read when emptied but can when intialised empty.

https://user-images.githubusercontent.com/4870868/132039689-5c2e455b-6f97-4bf0-a007-22a7fe14048f.mov

Existing V3 contracts don't experience this.

**Comment by austinabell** [comment]
The functionality of these structures hasn't changed and testing the same thing using v3 yields the same error using the repro you gave with v3. 

The issue with this test is that you're accessing the same underlying data of the unordered set with two initialized variables and when you delete from one set, the other does not know about this deletion and has an inconsistent state because it assumes a different amount of elements. You can think of this as similar to having two mutable references to the same struct, as you will run into race conditions. We can't enforce that this isn't done at compile-time, because the data is persisted.

There is no way around this because you would need to do a redundant read every time you access the struct (very wasteful on gas) AND assumes that the other struct writes the change immediately (this doesn't allow caching).

I've updated the test in your repro here https://github.com/austinabell/near-sdk-lookupmap-bug/commit/141818c0acc5d902e2e0074bc76f9f9511d8bf60 so that this condition isn't hit (and you can switch the v3 test to use the old pattern to see it also fails).

Thanks for flagging this as a pain point though, because this can be made more clear or we can go into detail about how these collections need to be used. I'll open up an issue in our documentation.

**Comment by evergreen-trading-systems** [comment]
Thanks for the response. I saw your changes and get it. Interestingly, haven't come across this problem before because compiler would have noticed.

I recreated the [same situation using hashmaps](https://github.com/evergreen-trading-systems/near-sdk-lookupmap-bug) to see the difference and found:

Inserting into a `hashmap` is `move` rather than `reference`. That would have prevented additional access.
When accessing `set` in `hashmap`, I specified `get_mut` to explicitly express mutation access otherwise it's a `reference`.

I know it's persisted but would be cool to simulate this. Anyway, this is not a bug.

**Comment by evergreen-trading-systems** [comment]
Actually this is just a mess. 

[This change demonstrates the same original problem](https://github.com/evergreen-trading-systems/near-sdk-lookupmap-bug/commit/c1663927fd515b7ed71499f0f3dbeeab014b4288). 

These interfaces don't do what they say and you should give them another name. You can't guarantee state and your types should reflect that. 

This isn't Rust anymore, it's vanilla javascript.

**Comment by evergreen-trading-systems** [comment]
```rust
let aid = AccountId::new_unchecked("a.testnet".to_lowercase());
let mut l:LookupMap<AccountId,UnorderedSet<u64>> = LookupMap::new(b"e".to_vec());
let mut us:UnorderedSet<u64> = UnorderedSet::new(b"dw".to_vec());
us.insert(&uid);
// us.insert(&uid2);
l.insert(&aid, &us);
 
// Whatever you do with this with not be reflect in `l`
let mut v = l.get(&aid).unwrap();

v.remove(&uid);

// madness 
l.insert(&aid, &v);

// won't break now
let k = l.get(&aid).unwrap();
println!("{}",k.is_empty());
```

**Comment by austinabell** [comment]
> On a deployed contract experiencing this, doesn't seem to be way to revert back from inconsistent state?

There is no default handling of this for the reasons given above. You can recover if you override the functionality of the data structure or create some sort of migration. It definitely won't be clean though unfortunately.

> Actually this is just a mess.
> 
> [This change demonstrates the same original problem](https://github.com/evergreen-trading-systems/near-sdk-lookupmap-bug/commit/c1663927fd515b7ed71499f0f3dbeeab014b4288).
> 
> These interfaces don't do what they say and you should give them another name. You can't guarantee state and your types should reflect that.
> 
> This isn't Rust anymore, it's vanilla javascript.

Yeah, honestly I'm a bit confused about your point here, as this is still the same case as before. Yes, you can trigger an inconsistent state if referencing the same state with multiple data structures, there is nothing you can do in Rust to disallow initializing more variables that use the same underlying storage.

If your point is around the fact that values are moved with the `HashMap` API, you will be happy to know that the next iteration of these structures are moving values in (as there will be a caching layer) and will make misusing this harder. I did not design the current version of the API, but there is was no reason to have the value moved in. It still cannot solve the issue of this being misused though. Rust can only guard against memory unsafety in memory, but there is no way of it providing a guarantee around the runtime interface which persists data as there is no way of translating which have references to it at compile time.

> All of this is unsafe code!

See the point above, there is no way to prohibit at compile time using storage outside of the context of Rust being memory unsafe. Please feel free to provide a suggestion, or indicate more specifically what you think should change, as it's possible I'm misunderstanding what you're getting at.

**Comment by evergreen-trading-systems** [comment]
Thanks for further elaborating. I expected the pointer to be released when [exiting scope](https://github.com/evergreen-trading-systems/near-sdk-lookupmap-bug/commit/c1663927fd515b7ed71499f0f3dbeeab014b4288#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759R19). I'd like to provide a solution to the problem of compile safety for persistent data access but I'd have to investigate deeply, no time.   That next release would make things better but for now, it's a silent but deadly gotcha. You answered the question though and this will be a good read for others who come across the same. I'll close.

**Comment by zcstarr** [comment]
Throwing a nod here, that I just hit a similar issue myself. This issue was immensely helpful in debugging. Thanks all
