### ISSUE TITLE
Add a note about dependencies in README.md

### ISSUE THREAD

**Issue by adsick** [near/near-sdk-rs#602]
Hi, I wanted to quickly get up and running with [https://examples.near.org/NFT](https://examples.near.org/NFT) , 
 but unfortunately compilation was not successful and I was getting errors very similar to #355 
 the error messages are not crystal clear, but it is possible to understand that my linux workstation misses some llvm and clang stuff,
 so after
 ```sudo dnf install llvm```
 ```sudo dnf install clang```
 things are now compiled, but dependencies should be listed in Readme.md 
 so others can clearly see what they need to start the job.

**Comment by HumbertoTM10** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/near-sdk-rs).

### My background and how it can be leveraged
I have 4 years working in development environments, have encountered several challenges, requests and teams focusing in reusable and efficient code, so that gives me a better understanding of the code and how to solve problems efficiently.


### How I plan on tackling this issue
In order to solve this issue, first I will resarch the project in order to have clear understanding of its functions and how it should perform so I can explain with details in the Read Me so it can be easily understood by the people how read it.

**Comment by BraCR10** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/near-sdk-rs).

### My background and how it can be leveraged
Hello, I would like to investigate the project to generate the corresponding documentation. According to the description, I have to document certain things related to the `llvm` and `clang` dependencies. It could definitely help with the problem and contribute to the project. I have had the opportunity to explore Rust, so I could handle or understand certain problems to improve documentation

### How I plan on tackling this issue
I plan to document in the Readme and test on my machine to verify the operation of the commands

**Comment by frol** [comment]
I don't think it is an issue anymore as it was part of near-sdk-sim, which got completely removed.
