### ISSUE TITLE
where is the log_str function?

### ISSUE THREAD

**Issue by kulame** [near/near-sdk-rs#638]
hi guys, i meet a rust error.

```rust
error[E0425]: cannot find function `log_str` in module `env`
  --> src/lib.rs:55:18
   |
55 |             env::log_str("Try again")
   |                  ^^^^^^^ not found in `env`
```

how can i use the log_str function?

**Comment by austinabell** [comment]
This was added in 4.0 of the SDK (see https://github.com/near/near-sdk-rs/blob/6ef1c4b0b2f37dfa5401bf10fda49bcd4c369d17/near-sdk/src/environment/env.rs#L504) so make sure you are using 4.0.0-pre.4 if you want to use this. Otherwise, can just use `env::log(b"some log")` and this will just be deprecated when/if you upgrade.
