### ISSUE TITLE
Move of `self` in 3.2.0 version of non_fungible_token

### ISSUE THREAD

**Issue by StanislavBreadless** [near/near-sdk-rs#657]
In 3.2.0 there is the following line of code that breaks the ability of other methods to call this method.

```
    fn nft_token(self, token_id: TokenId) -> Option<Token>;
```

Please note, `self` moves the value here. It seems to me that the version should be yanked

**Comment by austinabell** [comment]
> In 3.2.0 there is the following line of code that breaks the ability of other methods to call this method.
> 
> ```
>     fn nft_token(self, token_id: TokenId) -> Option<Token>;
> ```
> 
> Please note, `self` moves the value here. It seems to me that the version should be yanked

I don't think yanking it is a valid option since it only is a less ergonomic API for this use case, there are ways around this and people are relying on this version. There is nothing that is broken or buggy about this, it's just not the correct API.

If you require being on version 3 of the SDK (this has since been fixed) but need this change, let us know. I'm sure we can cut a release with this change and backport a few other things if there is demand for it :)

**Comment by StanislavBreadless** [comment]
@austinabell Yeah makes sense. Yanking is too radical indeed and in all other ways, it works totally fine :+1:

**Comment by StanislavBreadless** [comment]
I guess that if someone really needs that, they can copy-paste/rewrite the function on their side, so I I'll just close the issue. Thank you for your answer

**Comment by austinabell** [comment]
> I guess that if someone really needs that, they can copy-paste/rewrite the function on their side, so I I'll just close the issue. Thank you for your answer

Sorry for the inconvenience around this, yeah the easiest workaround would just be switching your impl from using the trait to just a regular `impl` and switching the signature to what you need. There will be no API changes from what you suggested and will still be compatible with the standard.

Let us know if there is anything we can help with this :)
