### ISSUE TITLE
Question about Strings in APIs

### ISSUE THREAD

**Issue by bitswell** [near/near-sdk-rs#684]
I see a lot of `String`'s used in contract parameters. Does this have to be the case? Could it be `&String` or `&str`. To put it another way, does the same data get deserialized with `&String`?

This leads to a lot of cloning when internally calling external API's.

**Comment by austinabell** [comment]
> I see a lot of `String`'s used in contract parameters. Does this have to be the case? Could it be `&String` or `&str`. To put it another way, does the same data get deserialized with `&String`?
> 
> This leads to a lot of cloning when internally calling external API's.

Absolutely you can! But note that if the function is public and directly callable, the type that you have a reference or mutable reference to (`&` or `&mut`) must be something that implements `BorshDeserialize` and is therefore owned.

For example:
```
    pub fn get(&self, key: &String) {
        // sth here
    }
```

within `#[near_bindgen]` works because `String` can be deserialized into, where:

```
    pub fn get(&self, key: &str) {
        // sth here
    }
```

does not because `str` is not sized and cannot be deserialized into, and it cannot infer that you wanted to deserialize as a `String` and then only get a reference to the `str`.

Any functions that are private and not externally visible to call into (any without `pub`) you can have whatever types you want because there is no codegen for these methods.

Hope this info helps :) let me know if there is anything I can clarify

**Comment by bitswell** [comment]
Thanks! That makes a lot of sense!

A follow up then would be what is the motivation of the `Promise` API to take an `AccountId` and not `&AccountId`?  I see in the recent PR to add events `Cow` was used to prevent clones.  I understand passing valid account ids, but shouldn't the internals use `Cow` or would this over complicate the API?

https://github.com/near/near-sdk-rs/blob/2d867cb27732fd680c40d18c9ef9a3b89eb4e0f5/near-sdk/src/promise.rs#L213

**Comment by austinabell** [comment]
> Thanks! That makes a lot of sense!
> 
> A follow up then would be what is the motivation of the `Promise` API to take an `AccountId` and not `&AccountId`? I see in the recent PR to add events `Cow` was used to prevent clones. I understand passing valid account ids, but shouldn't the internals use `Cow` or would this over complicate the API?
> 
> https://github.com/near/near-sdk-rs/blob/2d867cb27732fd680c40d18c9ef9a3b89eb4e0f5/near-sdk/src/promise.rs#L213

The reason why this can't be changed with the API's current form is:
1. `Promise` API relies on `Drop` to schedule the calls when it drops out of scope. This isn't a problem on its own but this would cause a lot of churn because a common pattern is to retrieve the `AccountId` within the current function, but then return the promise from the function and this is impossible to assign a lifetime in this case.
2. Can't use `Cow` for the same reason as above, but also this adds additional code size for this additional type to every contract, which isn't ideal.

We are making changes to how cross-contract calls happen, and this may come with a change to this Promise API, and this will be top on mind to make sure it is ergonomic.

**Comment by austinabell** [comment]
Closing because unactionable right now (re-open if you feel otherwise)
