### ISSUE TITLE
[EXT] Collections - Vector

### ISSUE THREAD

**Issue by near-arthur** [near/near-sdk-rs#716]
[https://docs.rs/near-sdk/3.1.0/near_sdk/collections/struct.Vector.html](https://docs.rs/near-sdk/3.1.0/near_sdk/collections/struct.Vector.html)

For each of the following functions, add an example code snippet:

*   pub fn len
*   pub fn new
*   pub fn clear
*   pub fn push
*   pub fn extend
*   pub fn get

Examples should be simple, easy-to-follow, and useful to make onboarding and learning Rust SDK as straightforward as possible. See array primitive for examples of code snippet examples: [https://doc.rust-lang.org/nightly/core/primitive.array.html](https://doc.rust-lang.org/nightly/core/primitive.array.html)), [https://doc.rust-lang.org/src/std/collections/hash/map.rs.html#784-790](https://doc.rust-lang.org/src/std/collections/hash/map.rs.html#784-790) for examples in code.

**Comment by austinabell** [comment]
Note that for all or most of the collection types, these are all legacy ones that will eventually be replaced by the [`near_sdk::store`](https://github.com/near/near-sdk-rs/tree/master/near-sdk/src/store) equivalents, so not sure if it's worth putting resources into.

The one exception to the new collections being documented with examples is actually the new Vector https://github.com/near/near-sdk-rs/blob/master/near-sdk/src/store/vec/mod.rs which could be improved.

Also, note that docs can be pulled from https://doc.rust-lang.org/std/vec/struct.Vec.html for the most part (esp for the new version because the API matches more closely than `near_sdk::collections::Vector`

**Comment by bugproof** [comment]
I don't really get why the new Vector doesn't use u64 anymore but u32, if you plan on having more than `u32::MAX` items you cannot do this with this change. I guess your option is only UnorderedMap/LookupMap
