### ISSUE TITLE
Investigate `.expect` potentially pulling in format code

### ISSUE THREAD

**Issue by ChaoticTempest** [near/near-sdk-rs#746]
Related to [https://github.com/near/near-sdk-rs/pull/745#discussion_r823157341](https://github.com/near/near-sdk-rs/pull/745#discussion_r823157341)

Investigate whether the following `.expect` call is pulling formatting code which would increase the code size:
 ```
 near_sdk::borsh::BorshSerialize::try_to_vec(&result).expect("Failed to serialize the return value using Borsh.")
 ```

**Comment by sn99** [comment]
Hi @frol I would like to be assigned this issue.

**Comment by sn99** [comment]
Hi @frol, I got busy over the weekend.

> Investigate whether the following `.expect` call is pulling formatting code which would increase the code size:

Yes it does, internally [`.expect(...)` calls `unwrap_failed(..., ...)`](https://doc.rust-lang.org/src/core/result.rs.html#1028-1030) which in turn [calls our beloved `panic!(...)`](https://doc.rust-lang.org/src/core/result.rs.html#1651), and [from the docs](https://doc.rust-lang.org/std/macro.panic.html):

> When using `panic!()` you can specify a string payload that is built using [formatting syntax].

This does seem to increase code size as stated in the [rustwasm book](https://rustwasm.github.io/docs/book/reference/code-size.html#avoid-string-formatting).

The book mentions to use something like:
```rust
#![allow(unused_variables)]
fn main() {
#[inline]
pub fn unwrap_abort<T>(o: Option<T>) -> T {
    use std::process;
    match o {
        Some(t) => t,
        None => process::abort(),
    }
}
}
```
Stating:

> Ultimately, panics translate into aborts in `wasm32-unknown-unknown` anyways, so this gives you the same behavior but without the code bloat.

But this would likely make us lose the message in `expect`.

On side note i was able to decrease the wasm file size by just adding:
```toml
[profile.release]
opt-level = 's'
codegen-units = 1
```
I can make a pr if needed.

**Comment by frol** [comment]
> The book mentions to use something like:

@sn99 Well, sure, we already have [`near_sdk::env::panic_str()`](https://docs.rs/near-sdk/5.0.0-alpha.1/near_sdk/env/fn.panic_str.html) for that, but we don't want to give up on the standard features. Thinking about it now I realized that `expect` requires formatting to Debug-format the error itself.

How big is the impact on the Wasm binary size afterall? My guess is that near-sdk-rs pulls it a ton of code that has `expect` in it, so adding a user code with `.expect` won't change the picture much. Also, consider using https://github.com/austinabell/nesdie in addition to near-sdk-rs to compare the sizes (e.g. with nesdie I was able to build [a meaningful contract in Rust that is under 1kb](https://github.com/frol/transfer-near-contract))

> On side note i was able to decrease the wasm file size by just adding:

These are recommended options when creating a new project: https://docs.near.org/sdk/rust/get-started#create-a-new-project, but since you mention it, I believe we missed to overcommunicate it enough. Where would you want to add it?

**Comment by TropicalDog17** [comment]
Hi @frol can I work on this issue? it seems the previous assignees was inactive for a while.

**Comment by frol** [comment]
@TropicalDog17 Sure. Reassigned it to you

**Comment by TropicalDog17** [comment]
Hi @frol, after replacing std `expect` with near-sdk's `panic_str` [here](https://github.com/TropicalDog17/near-sdk-rs/commit/2c6e1621b85281143067ed5dd73a52cbc5f00216)   and compile the `fungible_token` example, the wasm code size is reduced from 165.4KB to 165.1KB, which is 0.3KB (0.18%) reduction of code size. I'm not sure if it is significant or not, but actually remove the expect would decrease code size.
![image](https://github.com/user-attachments/assets/cdc631b3-7612-474c-b701-6217f2f4183d)

![image](https://github.com/user-attachments/assets/54a71207-3282-4d16-9418-53ea1ad21c46)

**Comment by frol** [comment]
@TropicalDog17 That is insignificant. Please, try replacing all `.expect()` calls in near-sdk-rs and in the code generated by near-sdk-macros, such as:

https://github.com/near/near-sdk-rs/blob/0f46b0d596bbd5173b2c698b1fd7d6f8a2fc9a11/near-sdk-macros/src/core_impl/code_generator/impl_item_method_info.rs#L122-L127

https://github.com/near/near-sdk-rs/blob/0f46b0d596bbd5173b2c698b1fd7d6f8a2fc9a11/near-sdk-macros/src/core_impl/code_generator/attr_sig_info.rs#L313

**Comment by TropicalDog17** [comment]
@frol 
After replacing essentially all .expect() calls here is the result,  ![image](https://github.com/user-attachments/assets/06e1a591-b0ce-4726-b974-24acc87ba7b3)

a decrease of 4kB, which is 2.42% reduction of code size compare to the original code in `master` branch.

**Comment by frol** [comment]
@TropicalDog17 I reviewed the PR, let's continue the discussion there
