### ISSUE TITLE
Make `Result` return value serialization print a deprecation warning

### ISSUE THREAD

**Issue by itegulov** [near/near-sdk-rs#748]
This is the logical continuation of https://github.com/near/near-sdk-rs/issues/574 - the path of gradually switching to `Result`-based error handling. As a next step, we need to make sure that using the legacy behavior of serializing a `Result` return value prints a deprecation warning.

**Comment by itegulov** [comment]
It does not seem like there is any sane way to make this a deprecation warning. So the next best thing would be giving a compilation error for users trying to serialize `Result` return values. This would be a more abrupt change, but at least we won't make any hidden breaking changes. @austinabell WDYT?

**Comment by austinabell** [comment]
> It does not seem like there is any sane way to make this a deprecation warning. So the next best thing would be giving a compilation error for users trying to serialize `Result` return values. This would be a more abrupt change, but at least we won't make any hidden breaking changes. @austinabell WDYT?

The negative to this is that if someone wanted to serialize a `Result` actually, they would be forced into using `#[handle_result]` with a return value of `Result<Result<X>>`. However, I don't think that's unreasonable since they would have to make the change in the next release, and this way, we can provide a targeted error message in the interim.

Your call!
