### ISSUE TITLE
How to check the network id on which the smart contract is deployed on 

### ISSUE THREAD

**Issue by siddharthborderwala** [near/near-sdk-rs#790]
I am making cross contract calls and based on the network id, the account IDs differ for the cross-contract calls. So, is there a way using which I can create a conditional and draft my code accordingly?

Thank in advance. I really appreciate all the help I have been getting from the maintainers in this repository, I just have to say it commendable work 🥳

**Comment by willemneal** [comment]
I'm not sure I follow completely.  But one way you can inform the contract which network it's on is to use a compile time feature.

```rust
if cfg!(feature = "testnet"){
  ...
} else {

}
```

then when compiling `--features testnet` to trigger the testnet case.

**Comment by austinabell** [comment]
Interesting, what would be the motivation to having different functionality based on the network type? There currently isn't any host function that exposes the network, and if you try to parse the suffix of the account ids in runtime this will not work in 100% of cases because implicit account ids do not have the network suffix.

If compile time differences that you can compile differently are acceptable, Willem's suggestion of the logic being separated by a feature is probably best if you're comfortable compiling each with the respective network deployment

**Comment by austinabell** [comment]
Closing because there isn't anything that can be done on the SDK to identify this -- hopefully answers given are sufficient. If not, feel free to re-open
