### ISSUE TITLE
Generate docs from the functions

### ISSUE THREAD

**Issue by swfsql** [near/near-sdk-rs#851]
For each method, expose or generate more information from `near_bindgen` into a module of the same name of the method:

*   Make the `Input` struct public. 
      *   Copy the function's docs into that struct.
    *   Allow for doc-commenting on the function's parameters (which rust doesn't allow), and move them over as docs to that struct's fields.
    *   Additionally derive a [JsonSchema](https://github.com/GREsau/schemars) for the struct. 
            *   This can be used to be a part of an automatic OpenAPI doc of that function.
    *   The simulation tests can use that to create the arguments that the function requires.
*   Create a trait that has a method with the same name as the original method, and also with the same parameters (except `self`). 
      *   This allows an automatic generic implementation that can help with the tests. In this way, some wrapper type (over the contract) can, after importing all of the contract's generated traits, to directly call the methods, and have the IDE to show all off the arguments, return with a defined type, and to be able to go to the function definition. In this scenario, the tests also don't need to use the `view`, `call` and `deploy` macros, nor to make usage of the `json` macro.
*   Implement a common trait for the `Input` that allows access to useful information, such as whether the function has no return, and so on. This information can later be used during the OpenAPI generation.
*   Also generate or implement JsonSchemas for all of the types inside of the sdk, since they can be depended upon by the contracts from the users.

I'm not sure of how a proper design would be, since this touches a lot of inner workings of the `near_bindgen` code generation; nor how it would interact with other parts of the system that are not json-based.

**Comment by willemneal** [comment]
Check out https://raen.dev, This already does mostly as you describe.  Even allow for validation of inputs.

Furthermore, this NEP, proposes use `wit` as the underlying contract interface.  Then schemas can be generated from it: https://gov.near.org/t/proposal-use-webassembly-interface-types-to-describe-all-standards-interfaces-and-application-contract-interface-aci/23256

**Comment by swfsql** [comment]
Whoa, thanks for sharing this! I didn't know of it, nor of the WIT format - it will probably be more general than the jsonschema/openapi ones, if I had to guess. I myself will try to learn more about those, even openapi itself is news to me!

And well, I actually made this issue after trying something out, after making a best-effort (messy) trial with this, but specifically with openapi. This is an [example](https://redocly.github.io/redoc/?url=https://gist.githubusercontent.com/swfsql/ebf93ddbf5743bb49dff8e5018b81e33/raw/ea53b11d6b71a01b4786769d9cb9d1d8fa71acaf/gistfile1.txt#tag/counter/operation/set) of what it could look like, if this can help with ideas and whatnot.

**Comment by zcstarr** [comment]
@willemneal  thanks for the shoutout. @swfsql  awesome. Documented interfaces are great. I have a some things going already with OpenRPC but on the static description side. 

We've done some work with using decorators in golang to automatically provide documentation for golang rpc interfaces. Filecoin lotus uses it currently for their interface https://github.com/filecoin-project/lotus/search?q=openrpc. Eth2 execution apis https://github.com/ethereum/execution-apis uses OpenRPC as well , it's basically what you mention openapi for json-rpc.

I have a repo where I've done this kind of annotation for near smart contracts 
https://github.com/shipsgold/open-rpc-near-client-generator
https://github.com/swappland/open-rpc-near-token-standards
https://github.com/swappland/swappland-market-contract-spec

https://open-rpc.org - just general info about open-rpc

We'd love to bring our OpenRPC Rust ecosystem back into parity with the rest of OpenRPC tooling. Aka do the same thing we've done with decorators in golang with macros in rust.  

The way it works in OpenRPC is we use the rpc.discover on endpoints to return back the spec itself, meaning you can request this json-rpc endpoint ("rpc.discover"), and then go to town. 

It makes it possible to then generate clients and servers straight from the docs, potentially straight from the rpc endpoint. 

In the Near case that could be straight from the contract itself. Additionally you can then using tooling like https://playground.open-rpc.org and https://inspector.open-rpc.org to interact with and get typesafe autofilled usage examples. 

The main thing, I think with the returning of a spec from the macro route is  the potential gas limitation on returning back a potentially large spec, which might need an extension to allow for some sort of framing/pagination. Those are I think workable details to sort through. 

Would love to chat about it we have discord for OpenRPC [here](https://discord.gg/ea4HKYm), I'm the same handle on discord.  Happy to carry this discussion here as well so people can chime in!

**Comment by willemneal** [comment]
> The main thing, I think with the returning of a spec from the macro route is the potential gas limitation on returning back a potentially large spec, which might need an extension to allow for some sort of framing/pagination. Those are I think workable details to sort through.

I've been injecting the types directly in the contract.  One example is the tenk contract which compressed as JSON is 5Kb and as wit 4.1 Kb (about to switch since the syntax is not stable).  Then you just download the contract costing no gas, though you pay some for the extra storage within the wasm.

**Comment by zcstarr** [comment]
> > The main thing, I think with the returning of a spec from the macro route is the potential gas limitation on returning back a potentially large spec, which might need an extension to allow for some sort of framing/pagination. Those are I think workable details to sort through.
> 
> I've been injecting the types directly in the contract. One example is the tenk contract which compressed as JSON is 5Kb and as wit 4.1 Kb (about to switch since the syntax is not stable). Then you just download the contract costing no gas, though you pay some for the extra storage within the wasm.

Very true that's the benefit of static generation, there's no reason why the tooling couldn't just download the wit and work things out from there. It would be probably be an easier operational step than going from macro to contract endpoint.

**Comment by swfsql** [comment]
That's amazing @zcstarr! Let alone the documentation, but also for the client building side of things! I also didn't know of OpenRPC, and I myself will be studying on it!

**Comment by swfsql** [comment]
One note is that I believe it would not be a problem for the tooling to use some macros to get the information, but I think it could avoid storing that info on the contract wasm binary (at least not immediately). For example, it could create a non-wasm binary that could generate the artifacts needed (wit/openapi/openrpc) and then create the files alongside the contract wasms. Mostly in the case for wit, I believe, maybe a different tool could then merge/insert the wit file into the contract if desired; or else the contract could use a url reference to the files as well - and this could work for all of wit/openapi/openrpc, if not even for all of those.

**Comment by austinabell** [comment]
> * Make the `Input` struct public.

This is a maintenance issue, we want to be able to update the functionality of deserialization without breaking APIs.

> The simulation tests can use that to create the arguments that the function requires.

So the issue with this generally is that you need to add `rlib` to your crate which disables lto and makes the wasm binary bloated, but also it requires that the tests you write reference the code directly.

It seems we are solving all of what you are looking to do and already have a PoC working for all tools connected through a schema file we are referring to as ABI (similar to Ethereum). We are moving toward making this production-ready and generally usable (current PRs https://github.com/near/near-sdk-rs/pull/831 and https://github.com/near/cargo-near/pull/2).

This is similar in concept to what Willem is describing, we are just using JSON instead of wit because it's more commonly used/read as well as the details of NEAR contracts not being expressible in wit. `wit` can be misleading for developers since it expresses the interface as if the parameters are passed directly into the exposed function, which is not how it works with the runtime. Because of this, tooling for wit won't translate so it's just like generating a DSL for expressing the semantics of the contract interface.

@zcstarr that's really interesting about the openrpc client generation, I think it could be cool for us to support adding the openrpc json target to our output. (Also able to add a wit target if there were use cases for that)

cc @itegulov wdyt about the open-rpc tooling? Do you think it's viable to allow that target through `cargo-near`, maybe under some feature flag? I wasn't aware of these tools previously, were you?

**Comment by willemneal** [comment]
> This is similar in concept to what Willem is describing, we are just using JSON instead of wit because it's more commonly used/read as well as the details of NEAR contracts not being expressible in wit. `wit` can be misleading for developers since it expresses the interface as if the parameters are passed directly into the exposed function, which is not how it works with the runtime. Because of this, tooling for wit won't translate so it's just like generating a DSL for expressing the semantics of the contract interface.

@austinabell `wit` can transform into the current ABI and vice versa.  Currently it assumes json serialization but attributes in the documentation allow for defining the serialization.

I take it that in your view they are incompatible  and thus is the reason this post hasn't been responded to: https://gov.near.org/t/proposal-use-webassembly-interface-types-to-describe-all-standards-interfaces-and-application-contract-interface-aci/23256

`wit` provides a human readable definition for the interface, while also having the added benefit of compressing smaller than the JSON schema will.

> wit can be misleading for developers since it expresses the interface as if the parameters are passed directly into the exposed function, which is not how it works with the runtime.

This is especially strange way to put it since this is exactly the abstraction we want developers to have.  They shouldn't need to know that the runtime is not implemented as if it was a function call.  This is why WIT is as an Application Contract Interface rather than an ABI. The standards should be defined as ACI's and WIT can provide this.

If you think that ABI and WIT are at odds please express that in the forum post or here.  I understand y'all are in a rush for nearcon, but I honestly beg you to consider working with the community.

**Comment by zcstarr** [comment]
@austinabell that'd be cool to support OpenRPC as well. If folks want a walkthrough of OpenRPC or have questions that need clarification feel free to ping me( I'm one of the maintainers of the project) or pop into the discord we're pretty active about answering questions https://discord.gg/ea4HKYm.

**Comment by swfsql** [comment]
@austinabell That's amazing, I'll be following on the progress!

> So the issue with this generally is that you need to add `rlib` to your crate which disables lto and makes the wasm binary bloated, but also it requires that the tests you write reference the code directly.

That is interesting, I searched online and it seems that Rust is missing some features about controlling those lib properties with relation to the targets. Interestingly, I changed `[lib.crate-type]` from `["cdylib", "rlib"]` to `["lib"]` and everything kept compiling, and indeed I got a smaller wasm binary. I was using `cargo build --lib --target wasm32-unknown-unknown --release` to build the contract, and `cargo build --bins` for other non-wasm binaries.

**Comment by austinabell** [comment]
> I take it that in your view they are incompatible and thus is the reason this post hasn't been responded to

Nope, @willemneal, not an intentional choice, just simply a lot going on and busy to read in-depth and add a thoughtful response to this.

> If you think that ABI and WIT are at odds please express that in the forum post or here. I understand y'all are in a rush for nearcon, but I honestly beg you to consider working with the community.

Nope, not at odds at all, this is why I suggested the possibility of incorporating with the path we are going. Nothing here is a standard or protocol change so no reason why these would be conflicting :) 

> I see, would this be in the sense that contracts that depend on the generation could stop compiling (or miss-compile)? Perhaps considering the increase of the major version for those cases could be a possibility.

@swfsql yes so it's increasing the surface area of an API that isn't necessarily polished or stable. It restricts improvements that can be made in the future for a very specific use case. Any changes would break usage which always would have to come with a major version change and effort in migration from developers who used it.

**Comment by willemneal** [comment]
@itegulov look forward to your feedback.  The way I view wis is ACI for higher level views like generated markdown, and a more easily embedded format.  Then fetch contracts and generate the JSON ABI to be consumed by the tooling. I'm almost done with `Wit` --> `JSON` and `JSON` --> `Wit` will be even easier.  So once we have them isomorphic all tooling will be available to devs.
