### ISSUE TITLE
Add manual trigger to compare compiled wasm builds against main branch

### ISSUE THREAD

**Issue by austinabell** [near/near-sdk-rs#881]
We need a way to easily compare the changes in wasm code size without relying on tracking specific wasm binary changes (#880).

Ideally, this is a manual trigger (maybe a GitHub actions trigger that runs on a specific comment on a PR) and this will build and compare the branch against the main branch and possibly outputs a comment with the summary in the PR.

How this is done doesn't really matter, but would be nice to have this data available for when we optimize the code sizes in the future.

**Comment by uint** [comment]
I started working on this, but it's turning out to be a bigger time sink than I expected. I need to keep a little tasklist somewhere!

- [x] MVP Python script that generates a markdown report given access to the source and target branches
- [ ] get the CI to work (tested on my fork since apparently I need to test on the default branch)
- [ ] refactor
- [ ] take advantage of [GitHub actions cache](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows) + don't leave running containers around

**Comment by frol** [comment]
Just wanted to share that we might want to look into the JS ecosystem where client bundle sizes are common to track, so tools like these exist: https://github.com/siddharthkp/bundlesize, https://github.com/bundlewatch/bundlewatch, https://github.com/marketplace/actions/compute-js-bundle-size

**Comment by uint** [comment]
About the specific tools linked: `compute-js-bundle-size` looks close to what we want, but the thing I'm writing is more about producing a "current branch vs master" report, and I don't see a way to get there nicely with that particular tool.

But good reminder I should spend more time checking out third-party tools before going to write my own. I'll take a look at what's there.
