### ISSUE TITLE
Cargo check fails with `__abi-embed`

### ISSUE THREAD

**Issue by austinabell** [near/near-sdk-rs#907]
changed with https://github.com/near/near-sdk-rs/pull/893, but it's really not ideal that the compilation with all features enabled fails. @miraclx would be awesome to find a workaround for this, or at the very least providing a better compilation error

**Comment by miraclx** [comment]
Had a workaround for this in an earlier iteration of implementing ABI embedding, that implemented a wrapper around `rustc` that activates a hidden cfg attribute only for the sdk crate when building with `cargo-near`. But I later removed it because it seemed overengineered.

Although, we can reintroduce and experiment with it again. Is this blocking for the sdk prerelease?

**Comment by austinabell** [comment]
> Had a workaround for this in an earlier iteration of implementing ABI embedding, that implemented a wrapper around `rustc` that activates a hidden cfg attribute only for the sdk crate when building with `cargo-near`. But I later removed it because it seemed overengineered.
> 
> Although, we can reintroduce and experiment with it again. Is this blocking for the sdk prerelease?

No, it's fine. It's a pre-release. Definitely no need to over-engineer. Just trying to avoid potential footguns of using or contributing to the SDK, not high priority.

Would be nice to have some fix by the stable 4.1, but nothing blocking
