### ISSUE TITLE
Don't use wee_alloc!

### ISSUE THREAD

**Issue by MaxGraey** [near/near-sdk-rs#910]
There are many reasons not to do it:

- Couple of memory leak bugs. [One of them](https://github.com/rustwasm/wee_alloc/issues/106)
- It's slow. It takes O(N) time for alloc due to simple linked list under the hood
- It's unmaintained, mostly 2 yeahs

Just use default dlmalloc

See more details:
https://github.com/rustwasm/wee_alloc/issues/107

**Comment by austinabell** [comment]
> There are many reasons not to do it:
> 
> * Couple of memory leak bugs. [One of them](https://github.com/rustwasm/wee_alloc/issues/106)

Memory leaks like this don't matter in our context since the functions are short-lived.

> * It's slow. It takes O(N) time for alloc due to simple linked list under the hood
> * It's unmaintained, mostly 2 yeahs

Agree wee_alloc isn't ideal, but tradeoffs with others. For example, in our context, we care a lot about compiled size, and wee_alloc is quite small. We could even go simpler with something like a bump allocator (since we don't care about de-allocations) or something more involved with a larger code size but more efficient, but it's opinionated.

> Just use default dlmalloc
> 
> See more details: [rustwasm/wee_alloc#107](https://github.com/rustwasm/wee_alloc/issues/107)

Haven't tested with dlmalloc, but intuitions are that it seems like it's not stable enough to use in prod right now and that it will be too bulky to use by default. Can definitely explore deeper though! In any case, we would not remove `wee_alloc` likely, but just support other options for allocators and possibly change the default to something, whether it be custom or some lib that's setup for the general case.

Related #457
