### ISSUE TITLE
After adding Chrono lib a have an error - wasm execution failed with error: FunctionCallError(CompilationError(PrepareError(Instantiate)))

### ISSUE THREAD

**Issue by Dumbris** [near/near-sdk-rs#915]
I have faced with an issue after adding chrono lib (https://docs.rs/chrono/latest/chrono/) into smart contract. I have an error  FunctionCallError(CompilationError(PrepareError(Instantiate))) permanently.

I created minimal example to reproduce problem - https://github.com/Dumbris/near_chrono_error
I just created new project using `npx create-near-app` command. And added these lines of code into the contract:
`use chrono::{DateTime, NaiveDateTime, Utc};` https://github.com/Dumbris/near_chrono_error/blob/b92a06112d211147e40dc6f74fca26979eee79a6/contract/src/lib.rs#L11
`let dt = Self::convert_timestamp_to_datetime(0);` https://github.com/Dumbris/near_chrono_error/blob/b92a06112d211147e40dc6f74fca26979eee79a6/contract/src/lib.rs#L41

```
fn convert_timestamp_to_datetime(timestamp: u64) -> DateTime<Utc> {
        let naive_date_time = NaiveDateTime::from_timestamp(timestamp as i64, 0);
        DateTime::<Utc>::from_utc(naive_date_time, Utc)
    }
```
https://github.com/Dumbris/near_chrono_error/blob/b92a06112d211147e40dc6f74fca26979eee79a6/contract/src/lib.rs#L46

After deploy to testnet any interaction with smart contract gives an error - wasm execution failed with error: FunctionCallError(CompilationError(PrepareError(Instantiate)))

Any ideas how to fix it?
If it's impossible for now, how can I known in advance which libraries will cause such error?

**Comment by austinabell** [comment]
So the issue is just that somewhere in this lib that's being compiled, it's using a host function which is not available on the NEAR runtime. Unfortunately, it would be very complex for us to check and assert this automatically, but hopefully we can do something to tighten that feedback loop.

In your case, what you can do is just disable the default features of `chrono`, and it will just work. Changing your dep in that repro to:
```
chrono = { version = "0.4", default-features = false }
```

compiles and runs fine. You can add back some of the default features if needed later, and try to find out which one is the incompatible, but hard to tell from a glance.

**Comment by Dumbris** [comment]
Thank you for clarifications and quick reply! I checked your solution it works 👍
